config/routes.rb
Rails.application.routes.draw do 
  
  get 'dashboard/index'
  root 'dashboard#index'

  
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  delete "logout", to: 'sessions#destroy'

  resources :tithes
  resources :groups
  resources :member_groups
  resources :department_members
  resources :departments
  resources :memberships
  resources :contributions
  resources :offertories
  resources :expenses
  resources :pledges
  resources :incomes
  resources :users
  
end

app/models/contribution.rb
class Contribution < ApplicationRecord
	validates :name, :purpose, :contribution_date, presence: true
	validates :amount, presence: true, numericality: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/department.rb
class Department < ApplicationRecord

	validates :name, presence: true, uniqueness: true
	has_many :department_members, dependent: :destroy
end

app/models/department_member.rb
class DepartmentMember < ApplicationRecord
  belongs_to :department

  validates :name, presence: true
  validates :department_id, presence: true
end

app/models/expense.rb
class Expense < ApplicationRecord
	validates :purpose, :expense_date, presence: true
	validates :amount, presence: true, numericality: true
end

app/models/group.rb
class Group < ApplicationRecord
	validates :group_name, presence: true, uniqueness: true

	has_many :member_groups, dependent: :destroy
end

app/models/income.rb
class Income < ApplicationRecord
	validates :totaltithe, :totalpledge, :totaloffertory, :totalcontribution, presence: true, numericality: true
	validates :month_year, presence: true
	

	def total_income
		Income.where(id: id).sum('totaltithe + totaloffertory + totalcontribution + totalpledge')
	end
end

app/models/member_group.rb
class MemberGroup < ApplicationRecord
  belongs_to :group

  validates :fullname, presence: true
  validates :group_id, presence: true
end

app/models/membership.rb
class Membership < ApplicationRecord
	extend FriendlyId
    friendly_id :firstname, use: :slugged

	validates :member_id, presence: true, uniqueness: true
	validates :firstname, :lastname, :gender, presence: true

	has_one_attached :image
	has_many :tithes, dependent: :destroy

end

app/models/offertory.rb
class Offertory < ApplicationRecord
	validates :amount, presence: true, numericality: true
	validates :description, :offertory_date, presence: true
end

app/models/pledge.rb
class Pledge < ApplicationRecord
	validates :membername, :payment, :pledge_date, :remarks, presence: true
	validates :amount, presence: true, numericality: true
end

app/models/tithe.rb
class Tithe < ApplicationRecord
  belongs_to :membership

  validates :membership_id, :tithe_date, presence: true
  validates :amount, presence: true, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	EMAIL_REGEX = /\A[^@\s]+@[^@\s]+\z/

	validates :email, presence: true, uniqueness: true, format: {with: EMAIL_REGEX }
	validates :user_type, presence: true
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_membership, only: [:show, :edit, :update, :destroy]
  
  def index
    @q = Membership.ransack(params[:q])
    @pagy, @memberships = pagy(@q.result(distinct: true), items: 15)
  end

  def new
  	@membership = Membership.new
  end

  def create
  	@membership = Membership.new(membership_params)

  	if @membership.save
  	  redirect_to memberships_path, notice: "Member added successfully"
  	  else
  	  render :new	
  	end
  end

  def show
  end

  def edit
  end

  def update

  	if @membership.update(membership_params)
  	 redirect_to membership_path, notice: "Member updated successfully"
  	 else
  	 render :edit	
  	end
  end

  def destroy
  	@membership.destroy
  	redirect_to memberships_path, notice: "Member deleted successfully"
  end

  private

  def set_membership
    @membership = Membership.friendly.find(params[:id])
  end

  def membership_params
  	params.require(:membership).permit(:image, :member_id, :firstname, :lastname, :othernames, :title, :position, :gender, :date_of_birth, :primary_phone_number, :other_phone_number, :email, :hometown, :residential_location, :occupation, :marital_status, :work_place, :year_joining_church)	
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/income_helper.rb
module IncomeHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tithes_helper.rb
module TithesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/memberships/_form.html.erb
<h1 class="font-bold">Membership</h1>
<p class="text-sm">Membership > Add Member</p>

<div class="mt-8">
	<%= form_with model: @membership,local: true do |f| %>
        <% if @membership.errors.any? %>
         <div class="max-w-lg mx-auto px-4 py-3 leading-normal text-red-700 bg-red-100 rounded-lg" role="alert">
          <% @membership.errors.full_messages.each do |message|%>
            <div class="text-center"><%= message %></div>
         <% end %>
         </div>
    <% end %>

    <div class="bg-white px-4 max-w-lg rounded-t p-5 border-t-2 border-blue-500 mx-auto mt-3">

		<div>
		   <%= f.label :image %>
		   <%= f.file_field :image, class: 'block focus:outline-none mb-2' %>	
		</div>

		<div>
		   <%= f.label :member_Id %>
		   <%= f.text_field :member_id, class: 'border border-gray-300 block w-full rounded px-2 py-1 focus:outline-none focus:border-blue-100 mb-2' %>	
		</div>

		<div>
		   <%= f.label :title %>
		   <%= f.select :title, options_for_select(['Mr.', 'Mrs.', 'Ms.'], selected: @membership.title), {:include_blank => ''}, class: 'border border-gray-300 block w-full rounded px-2 py-1 focus:outline-none focus:border-blue-100 mb-2'  %>
		</div>

		<div> 
		   <%= f.label :firstname %>
		   <%= f.text_field :firstname, class: 'border border-gray-300 block w-full rounded px-2 py-1 focus:outline-none focus:border-blue-100 mb-2' %>
		</div>

		<div>
		   <%= f.label :lastname %>
		   <%= f.text_field :lastname, class: 'border border-gray-300 block w-full rounded px-2 py-1 focus:outline-none focus:border-blue-100 mb-2' %>
		</div>

		<div> 
		   <%= f.label :othernames %>
		   <%= f.text_field :othernames, class: 'border border-gray-300 block w-full rounded px-2 py-1 focus:outline-none focus:border-blue-100 mb-2' %>	
		</div>

		<div>  
		   <%= f.label :gender %>
		   <%= f.select :gender, options_for_select(['Male', 'Female'], selected: @membership.gender), {:include_blank => ''}, class: 'border border-gray-300 block w-full rounded px-2 py-1 focus:outline-none focus:border-blue-100 mb-2' %>
		</div>

		<div>
		   <%= f.label :date_of_birth %>
		   <%= f.date_field :date_of_birth, selected: @membership.date_of_birth, class: 'border border-gray-300 block w-full rounded px-2 py-1 focus:outline-none focus:border-blue-100 mb-2' %>
		</div>

		<div>	
		   <%= f.label :primary_phone_number %>
		   <%= f.telephone_field :primary_phone_number, class: 'border border-gray-300 block w-full rounded px-2 py-1 focus:outline-none focus:border-blue-100 mb-2' %>
		</div>

		<div>
		   <%= f.label :other_phone_number %>
		   <%= f.telephone_field :other_phone_number, class: 'border border-gray-300 block w-full rounded px-2 py-1 focus:outline-none focus:border-blue-100 mb-2' %>	
		</div>

		<div>
		   <%= f.label :email %>
		   <%= f.email_field :email, class: 'border border-gray-300 block w-full rounded px-2 py-1 focus:outline-none focus:border-blue-100 mb-2' %>	
		</div>

		<div>
		   <%= f.label :hometown %>
		   <%= f.text_field :hometown, class: 'border border-gray-300 block w-full rounded px-2 py-1 focus:outline-none focus:border-blue-100 mb-2' %>
		</div>

		<div>
		   <%= f.label :residential_location %>
		   <%= f.text_area :residential_location, class: 'border border-gray-300 block w-full rounded px-2 py-1 focus:outline-none focus:border-blue-100 mb-2' %>	
		</div>

		<div>
		   <%= f.label :occupation %>
		   <%= f.text_field :occupation, class: 'border border-gray-300 block w-full rounded px-2 py-1 focus:outline-none focus:border-blue-100 mb-2' %>	
		</div>

		<div>
		   <%= f.label :marital_status %>
		   <%= f.select :marital_status, options_for_select(['Single', 'Married'], selected: @membership.marital_status), {:include_blank => ''}, class: 'border border-gray-300 block w-full rounded px-2 py-1 focus:outline-none focus:border-blue-100 mb-2' %>	
		</div>

		<div>
		   <%= f.label :place_of_work %>
		   <%= f.text_field :work_place, class: 'border border-gray-300 block w-full rounded px-2 py-1 focus:outline-none focus:border-blue-100 mb-2' %>	
		</div>

		<div>
		   <%= f.label :Member_position %>
		   <%= f.text_field :position, class: 'border border-gray-300 block w-full rounded px-2 py-1 focus:outline-none focus:border-blue-100 mb-2' %>
		</div>

		<div>
		   <%= f.label :year_joining_church %>
		   <%= f.text_field :year_joining_church, class: 'border border-gray-300 block w-full rounded px-2 py-1 focus:outline-none focus:border-blue-100 mb-4' %>	
		</div>
		
		<div>
		   <%= f.submit "Create Member", class: "bg-transparent hover:bg-blue-500 text-blue-500 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded cursor-pointer" %>	
		</div>
      <% end %>
    </div>
</div>

app/views/memberships/edit.html.erb
<h1>Memberships#edit</h1>
<p>Find me in app/views/memberships/edit.html.erb</p>

app/views/memberships/index.html.erb
<div class="mt-5">
    <%= link_to "Add Membership", new_membership_path, class: 'bg-blue-500 p-2 text-white hover:bg-blue-600' %>
</div>

<%= search_form_for @q do |f| %>
	<div class="flex float-right mb-2 mt-3">
      <%= f.search_field :firstname_or_lastname_or_member_id_or_position_cont, class: 'focus:outline-none focus:ring-1 focus:ring-gray-400 p-1 w-60 rounded-l',  placeholder: 'Search...' %>
  
       <%= button_tag(type: "Search", class: "border  bg-white rounded-r hover:border-gray-700") do %>
       <svg class="w-6 h-6 text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
       <% end %>
<% end %>
    </div>


<div class="w-full shadow rounded-lg overflow-auto mt-5 border-t-2 border-gray-500">
	<table class="w-full bg-white">
	<thead>
		<tr class="border-b-2 border-gray-200">
			<th class="text-left px-3 py-2">Id</th>
			<th class="text-left px-4 py-2">Pic</th>
			<th class="text-left px-3 py-2">Name</th>
			<th class="text-left px-3 py-2">Membership No.</th>
			<th class="text-left px-3 py-2">Position</th>
			<th class="text-left px-3 py-2">Phone No.</th>
			<th class="text-left px-3 py-2" colspan="3">Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @memberships.each do |membership| %>
		<tr class="border-b border-gray-200 hover:bg-gray-100">
			<td class="px-3"><%= membership.id %></td>
			<td class="px-3"><%= image_tag(membership.image, :size => '50x50') if membership.image.attached? %></td>
			<td class="px-3"><%= membership.firstname + " " + membership.lastname + " " + membership.othernames %></td>
			<td class="px-3"><%= membership.member_id %></td>
			<td class="px-3"><%= membership.position %></td>
			<td class="px-3"><%= membership.primary_phone_number %></td>
			<td class="flex px-3 mt-2"><%= link_to membership_path(membership.slug) do %>
				<svg class="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"></path></svg>
				<% end %>
			
			   <%= link_to edit_membership_path(membership.slug) do %>
				<svg class="w-5 h-5 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"></path></svg>
				<% end %>
			
			   <%= button_to membership_path(membership.id), method: :delete, data: {confirm: "Are you sure you want to delete?"} do %>
				 <svg class="w-5 h-5 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg>
				<% end %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

</div>
	
<div class="mt-2">
<%= pagy_nav(@pagy).html_safe %>
</div>

  
  
  
  

app/views/memberships/show.html.erb
<div class="grid grid-cols-3 mt-3">
	<div class="bg-white w-60 h-60 rounded-t p-3 border-t-2 border-blue-500">
		<div class="flex justify-center">
		  
		   <%= image_tag(@membership.image, :class => 'h-24 w-24 rounded-full mb-3 p-1 border border-2') if @membership.image.attached?  %>
		</div>
		<div class="text-center">
			<h3 class="text-sm bold mb-2"><%= @membership.firstname %> <%= @membership.lastname %> <%= @membership.othernames %></h3>
		</div>
		<div class="flex justify-center">
			<button class="bg-blue-200 text-center text-white px-2"><%= @membership.position %></button>
		</div>
		<div class="flex mt-2 space-x-2 justify-center">
			<svg class="w-4 h-4 mt-1" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z"></path></svg>
			<span><%= @membership.primary_phone_number %></span>
		</div>	
	</div>

	<div class="col-span-2">
		<div class="bg-white w-full rounded-t">
		 <div class="container mx-auto p-2 mb-4" x-data="{ tab: 'tab1' }">
        <ul class="flex border-b mt-2" >
            <li class="-mb-px mr-1">
                <a
                    class="inline-block rounded-t py-2 px-4 font-semibold hover:text-blue-800"  
                    :class="{ 'bg-white text-blue-700 border-l border-t border-r' : tab === 'tab1' }"
                    href="#"                        
                    @click.prevent="tab = 'tab1'"
                >Basic Info</a>
            </li>
            <li class="-mb-px mr-1">
                <a
                    class="inline-block py-2 px-4 text-blue-500 hover:text-blue-800 font-semibold"
                    :class="{ 'bg-white text-blue-700 border-l border-t border-r' : tab === 'tab2' }"
                    href="#"
                    @click.prevent="tab = 'tab2'"
                >Church</a
                >
            </li>
            <li class="-mb-px mr-1">
                <a
                    class="inline-block py-2 px-4 text-blue-500 hover:text-blue-800 font-semibold"
                    :class="{ 'bg-white text-blue-700 border-l border-t border-r' : tab === 'tab3' }"
                    href="#" 
                    @click.prevent="tab = 'tab3'"
                >Work</a
                >
            </li>
        </ul>
        <div class="content bg-white px-4 py-4 border-l border-r border-b pt-4 text-gray-500">
            <div x-show="tab === 'tab1'">
            	<h2 class="font-semibold">Member Basic Info</h2>
            	<table class="border w-full mt-2">
            		
            			<tr class="border">
            				<td class="border bg-gray-100 p-1">Membership ID</td>
            				<td class="p-1"><%= @membership.member_id %></td>
            			</tr>
                        <tr class="border">
                            <td class="border bg-gray-100 p-1">Title</td>
                            <td class="p-1"><%= @membership.title %></td>
                        </tr>
            			<tr class="border">
            				<td class="border bg-gray-100 p-1">Gender</td>
            				<td class="p-1"><%= @membership.gender %></td>
            			</tr>
                        <tr class="border">
                            <td class="border bg-gray-100 p-1">Marital Status</td>
                            <td class="p-1"><%= @membership.marital_status %></td>
                        </tr>
            			<tr class="border">
            				<td class="border bg-gray-100 p-1">D.O.B</td>
            				<td class="p-1"><%= @membership.date_of_birth %></td>
            			</tr>
            			<tr class="border">
            				<td class="border bg-gray-100 p-1">Email</td>
            				<td class="p-1"><%= @membership.email %></td>
            			</tr>
            			<tr class="border">
            				<td class="border bg-gray-100 p-1">Other Phone number</td>
            				<td class="p-1"><%= @membership.other_phone_number %></td>
            			</tr>
            			<tr class="border">
            				<td class="border bg-gray-100 p-1">Place of residence</td>
            				<td class="p-1"><%= @membership.residential_location %></td>
            			</tr>
            			<tr class="border">
            				<td class="border bg-gray-100 p-1">Hometown</td>
            				<td class="p-1"><%= @membership.hometown %></td>
            			</tr>
            	</table>
            </div>
            <div x-show="tab === 'tab2'">
               <h2 class="font-semibold">Church</h2>
            	<table class="border w-full mt-2">        		
            			<tr class="border">
            				<td class="border bg-gray-100 p-1">Year Joining Church</td>
            				<td class="p-1"><%= @membership.year_joining_church %></td>
            			</tr>
            	</table>
            </div>                
            <div x-show="tab === 'tab3'">
               <h2 class="font-semibold">Work</h2>
            	<table class="border w-full mt-2">        		
            			<tr class="border">
            				<td class="border bg-gray-100 p-1">Place of work</td>
            				<td class="p-1"><%= @membership.work_place %></td>
            			</tr>
            			<tr class="border">
            				<td class="border bg-gray-100 p-1">Occupation</td>
            				<td class="p-1"><%= @membership.occupation %></td>
            			</tr>
            	</table>
            </div>       
        </div>
       </div>
	 </div>
	</div>
</div>