config/routes.rb
Rails.application.routes.draw do 
  
  get 'dashboard/index'
  root 'dashboard#index'

  
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  delete "logout", to: 'sessions#destroy'

  resources :tithes
  resources :groups
  resources :member_groups
  resources :department_members
  resources :departments
  resources :memberships
  resources :contributions
  resources :offertories
  resources :expenses
  resources :pledges
  resources :incomes
  resources :users
  
end

app/models/contribution.rb
class Contribution < ApplicationRecord
	validates :name, :purpose, :contribution_date, presence: true
	validates :amount, presence: true, numericality: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/department.rb
class Department < ApplicationRecord

	validates :name, presence: true, uniqueness: true
	has_many :department_members, dependent: :destroy
end

app/models/department_member.rb
class DepartmentMember < ApplicationRecord
  belongs_to :department

  validates :name, presence: true
  validates :department_id, presence: true
end

app/models/expense.rb
class Expense < ApplicationRecord
	validates :purpose, :expense_date, presence: true
	validates :amount, presence: true, numericality: true
end

app/models/group.rb
class Group < ApplicationRecord
	validates :group_name, presence: true, uniqueness: true

	has_many :member_groups, dependent: :destroy
end

app/models/income.rb
class Income < ApplicationRecord
	validates :totaltithe, :totalpledge, :totaloffertory, :totalcontribution, presence: true, numericality: true
	validates :month_year, presence: true
	

	def total_income
		Income.where(id: id).sum('totaltithe + totaloffertory + totalcontribution + totalpledge')
	end
end

app/models/member_group.rb
class MemberGroup < ApplicationRecord
  belongs_to :group

  validates :fullname, presence: true
  validates :group_id, presence: true
end

app/models/membership.rb
class Membership < ApplicationRecord
	extend FriendlyId
    friendly_id :firstname, use: :slugged

	validates :member_id, presence: true, uniqueness: true
	validates :firstname, :lastname, :gender, presence: true

	has_one_attached :image
	has_many :tithes, dependent: :destroy

end

app/models/offertory.rb
class Offertory < ApplicationRecord
	validates :amount, presence: true, numericality: true
	validates :description, :offertory_date, presence: true
end

app/models/pledge.rb
class Pledge < ApplicationRecord
	validates :membername, :payment, :pledge_date, :remarks, presence: true
	validates :amount, presence: true, numericality: true
end

app/models/tithe.rb
class Tithe < ApplicationRecord
  belongs_to :membership

  validates :membership_id, :tithe_date, presence: true
  validates :amount, presence: true, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	EMAIL_REGEX = /\A[^@\s]+@[^@\s]+\z/

	validates :email, presence: true, uniqueness: true, format: {with: EMAIL_REGEX }
	validates :user_type, presence: true
end

app/controllers/department_members_controller.rb
class DepartmentMembersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_department_member, only: [:edit, :update, :destroy]
  
  def index
  	 @q = DepartmentMember.ransack(params[:q])
     @pagy, @department_members = pagy(@q.result(distinct: true), items: 10)
  end

  def new
  	@department_member = DepartmentMember.new
  end

  def create
  	@department_member = DepartmentMember.new(departmentmember_params)

  	if @department_member.save
  		redirect_to department_members_path, notice: "Department Member added successfully"
  	else
  		render :new
  	end
  end

  def show  
  end

  def edit
  end

  def update
    if @department_member.update(departmentmember_params)
     redirect_to department_members_path, notice: "Department Member updated successfully"
    else
      render :edit
    end
  end

  def destroy
    @department_member.destroy
    redirect_to department_members_path, notice: "Department Member deleted"
  end

  private

  def set_department_member
    @department_member = DepartmentMember.find(params[:id])
  end

  def departmentmember_params
  	params.require(:department_member).permit(:name, :department_id)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/department_members_helper.rb
module DepartmentMembersHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/income_helper.rb
module IncomeHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tithes_helper.rb
module TithesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/department_members/_form.html.erb
<h1 class="font-bold">Department Member</h1>
<p class="text-sm">Department Member > Add Department Member</p>

<div class="mt-8">
   <%= form_with model: @department_member, local: true do |f| %>
        <% if @department_member.errors.any? %>
         <div class="max-w-lg mx-auto px-4 py-3 leading-normal text-red-700 bg-red-100 rounded-lg" role="alert">
          <% @department_member.errors.full_messages.each do |message|%>
            <div class="text-center"><%= message %></div>
         <% end %>
         </div>
    <% end %>

	<div class="bg-white px-4 max-w-lg rounded-t p-5 border-t-2 border-blue-500 mx-auto mt-3">
	 
		<div>
		   <%= f.label :fullname %>
	       <%= f.text_field :name, class: 'border border-gray-300 block w-full rounded px-2 py-1 focus:outline-none focus:border-blue-100 mb-2' %>
		</div>

		<div>		
	       <%= f.label :Department %>
	       <%= f.select :department_id, options_for_select(Department.all.map{|c| [c.name, c.id]},  selected: @department_member.department_id), {:include_blank => '--Select One --'}, class: 'border border-gray-300 block w-full rounded px-2 py-1 focus:outline-none focus:border-blue-100 mb-2'  %>
		</div>

		<div>
			<%= f.submit "Create", class: "bg-transparent hover:bg-blue-500 text-blue-500 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded cursor-pointer" %>
		</div>	
      <% end %>
	</div>	
</div> 

app/views/department_members/index.html.erb
<div class="mt-5">
    <%= link_to "Add Department Member", new_department_member_path, class: 'bg-blue-500 p-2 text-white hover:bg-blue-600' %>
</div>


<%= search_form_for @q do |f| %>
<div class="flex float-right mb-2 mt-3">
  <%= f.search_field :name_or_department_name_cont, class: 'focus:outline-none focus:ring-1 focus:ring-gray-400 p-1 w-60 rounded-l',  placeholder: 'Search...' %>
   <%= button_tag(type: "Search", class: "border  bg-white rounded-r hover:border-gray-700") do %>
 <svg class="w-6 h-6 text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
  <% end %>
<% end %>
</div>

<div class="w-full shadow rounded-lg overflow-auto mt-5 border-t-2 border-gray-500">
   <table class="w-full bg-white">
	<thead>
		<tr class="border-b-2 border-gray-200">
			<th class="text-left px-3 py-2">Id</th>
			<th class="text-left px-3 py-2">Name</th>
			<th class="text-left px-3 py-2">Department</th>
			<th class="text-left px-3 py-2" colspan="2">Action</th>
		</tr>
	</thead>
	<tbody>
		<% @department_members.each do |departmentmember| %>

		<tr class="border-b border-gray-200 hover:bg-gray-100">
			<td class="px-3 py-1"><%= departmentmember.id %></td>
			<td class="px-3 py-1"><%= departmentmember.name %></td>
			<td class="px-3 py-1"><%= departmentmember.department.name %></td>
			<td class="flex px-3 mt-2"><%= link_to edit_department_member_path(departmentmember.id) do %>
				<svg class="w-5 h-5 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"></path></svg>
				<% end %>
			
			    <%= button_to department_member_path(departmentmember.id), method: :delete, data: {confirm: "Are you sure you want to delete?"} do %>
				 <svg class="w-5 h-5 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg>
				<% end %>
			</td>
		</tr>
        <% end %>
	</tbody>
</table>
</div>

<div class="mt-2">
<%= pagy_nav(@pagy).html_safe %>
</div>