config/routes.rb
Rails.application.routes.draw do 
  
  get 'dashboard/index'
  root 'dashboard#index'

  
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  delete "logout", to: 'sessions#destroy'

  resources :tithes
  resources :groups
  resources :member_groups
  resources :department_members
  resources :departments
  resources :memberships
  resources :contributions
  resources :offertories
  resources :expenses
  resources :pledges
  resources :incomes
  resources :users
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contribution.rb
class Contribution < ApplicationRecord
	validates :name, :purpose, :contribution_date, presence: true
	validates :amount, presence: true, numericality: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/department.rb
class Department < ApplicationRecord

	validates :name, presence: true, uniqueness: true
	has_many :department_members, dependent: :destroy
end

app/models/department_member.rb
class DepartmentMember < ApplicationRecord
  belongs_to :department

  validates :name, presence: true
  validates :department_id, presence: true
end

app/models/expense.rb
class Expense < ApplicationRecord
	validates :purpose, :expense_date, presence: true
	validates :amount, presence: true, numericality: true
end

app/models/group.rb
class Group < ApplicationRecord
	validates :group_name, presence: true, uniqueness: true

	has_many :member_groups, dependent: :destroy
end

app/models/income.rb
class Income < ApplicationRecord
	validates :totaltithe, :totalpledge, :totaloffertory, :totalcontribution, presence: true, numericality: true
	validates :month_year, presence: true
	

	def total_income
		Income.where(id: id).sum('totaltithe + totaloffertory + totalcontribution + totalpledge')
	end
end

app/models/member_group.rb
class MemberGroup < ApplicationRecord
  belongs_to :group

  validates :fullname, presence: true
  validates :group_id, presence: true
end

app/models/membership.rb
class Membership < ApplicationRecord
	extend FriendlyId
    friendly_id :firstname, use: :slugged

	validates :member_id, presence: true, uniqueness: true
	validates :firstname, :lastname, :gender, presence: true

	has_one_attached :image
	has_many :tithes, dependent: :destroy

end

app/models/offertory.rb
class Offertory < ApplicationRecord
	validates :amount, presence: true, numericality: true
	validates :description, :offertory_date, presence: true
end

app/models/pledge.rb
class Pledge < ApplicationRecord
	validates :membername, :payment, :pledge_date, :remarks, presence: true
	validates :amount, presence: true, numericality: true
end

app/models/tithe.rb
class Tithe < ApplicationRecord
  belongs_to :membership

  validates :membership_id, :tithe_date, presence: true
  validates :amount, presence: true, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	EMAIL_REGEX = /\A[^@\s]+@[^@\s]+\z/

	validates :email, presence: true, uniqueness: true, format: {with: EMAIL_REGEX }
	validates :user_type, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:edit, :update, :destroy]
  
  def index
  	@pagy, @groups = pagy(Group.all, items: 10)
  end

  def new
    @group = Group.new
  end

  def create
  	@group = Group.new(group_params)

  	if @group.save
  		redirect_to groups_path, notice: "Group #{@group.group_name} added successfully"
  	else
  		render :new
  	end
  end

  def show   
  end

  def edit
  end

  def update
    if @group.update(group_params)
     redirect_to groups_path, notice: "Group #{@group.group_name} updated successfully"
    else
      render :edit
    end
  end

  def destroy 
    @group.destroy
    redirect_to groups_path, notice: "Group #{@group.group_name} deleted" 
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
  	params.require(:group).permit(:group_name)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/income_helper.rb
module IncomeHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tithes_helper.rb
module TithesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<h1 class="font-bold">Group</h1>
<p class="text-sm">Group > Add New Group</p> 

<div class="mt-8">
     <%= form_with model: @group, local: true do |f| %>
        <% if @group.errors.any? %>
         <div class="max-w-lg mx-auto px-4 py-3 leading-normal text-red-700 bg-red-100 rounded-lg" role="alert">
          <% @group.errors.full_messages.each do |message|%>
            <div class="text-center"><%= message %></div>
         <% end %>
         </div>
    <% end %> 
    <div class="bg-white px-4 max-w-lg rounded-t p-5 border-t-2 border-blue-500 mx-auto mt-3">
        <div>
          <%= f.label :group %>
          <%= f.text_field :group_name, class: 'border border-gray-300 block w-full rounded px-2 py-1 focus:outline-none focus:border-blue-100 mb-2'  %>
        </div>

        <div>
          <%= f.submit "Create a group", class: "bg-transparent hover:bg-blue-500 text-blue-500 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded cursor-pointer" %>
        </div>  
      <% end %>
    </div>
 
</div>

app/views/groups/index.html.erb
<div class="mt-5">
    <%= link_to "Add Group", new_group_path, class: 'bg-blue-500 p-2 text-white hover:bg-blue-600' %>
</div>


<div  class="w-full shadow rounded-lg overflow-auto mt-5 border-t-2 border-gray-500">
 <table class="w-full bg-white">
	<thead>
		<tr class="border-b-2 border-gray-200">
			<th class="text-left px-3 py-2">Id</th>
			<th class="text-left px-3 py-2">Group Name</th>
			<th class="text-left px-3 py-2" colspan="2">Action</th>
		</tr>
	</thead>
	<tbody>
	  <% @groups.each do |group| %>
		<tr class="border-b border-gray-200 hover:bg-gray-100">
			<td class="px-3 py-1"><%= group.id %></td>
			<td class="px-3 py-1"><%= link_to group.group_name %></td>
			<td class="flex px-3 mt-2"><%= link_to edit_group_path(group.id) do %>
				<svg class="w-5 h-5 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"></path></svg>
				<% end %>
			    <%= button_to group_path(group.id), method: :delete, data: {confirm: "Are you sure you want to delete?"} do %>
				 <svg class="w-5 h-5 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg>
				<% end %>
			</td>
		</tr>
	</tbody>
	  <% end %>
</table>	
</div>

<div class="mt-2">
  <%= pagy_nav(@pagy).html_safe %>	
</div>